#ifndef auto_schedule_false_SCHEDULE_H
#define auto_schedule_false_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by 
// for target=x86-64-linux-avx-avx2-f16c-fma-sse41  // NOLINT
// with machine_params=

#include "Halide.h"


inline void apply_schedule_auto_schedule_false(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    // No autoscheduler has been run for this Generator.

}

#endif  // auto_schedule_false_SCHEDULE_H
